title: Loomio Help
baseURL: https://help.loomio.org
languageCode: en-NZ
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
theme: loomio-hugo-theme
params:
  repoName: loomio/loomio_help
  matomoId: 3
  useCategories: false
  canEdit: true
languages:
  en:
    languageName: English
    weight: 1
  es:
    languageName: Español
    weight: 2
  fr:
    languageName: Français
    weight: 3

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
